### PR TITLE
Generator creates a `.gitignore`

### LINKED ISSUE #2: Generator should create a .gitignore
The generator should probably create a .gitignore, containing at least the pip library directory.

### PR DESCRIPTION
**Pull request by SpainTrain**
* Add .gitignore file to app template
* Fix and DRY tests
* Fix license (SPDX-format string)
* Use latest `yeoman-generator` package (needed for tests)

Closes #2

### CODE REVIEW

**Comment by SpainTrain** [comment]
Hmm, unsure why Travis is not testing this PR https://travis-ci.org/jonparrott/Generator-Ferris-3/pull_requests

**Comment by jonparrott** [comment]
LGTM, thank you.

**Comment by SpainTrain** [comment]
:+1: Thanks for merging.  

FYI, you can have travis publish to npm automatically - http://docs.travis-ci.com/user/deployment/npm/

**Comment by jonparrott** [comment]
This project isn't currently setup for travis, but if you want to submit a PR to add it I'll gladly merge.

**Pull request merged**
